class HeadsUpData {
  static final List<String> words = [
    // --- VERBS / ACTIONS (Easy to Act) ---
    "EATING SPAGHETTI", "BRUSHING TEETH", "DRIVING A CAR", "FLYING A KITE",
    "PLAYING TENNIS", "SWIMMING IN COLD WATER", "CLIMBING A MOUNTAIN",
    "FISHING", "PAINTING A WALL", "TYPING FAST", "SHUFFLING CARDS",
    "CHOPPING ONIONS", "BAKING A CAKE", "VACUUMING", "MOPPING THE FLOOR",
    "IRONING A SHIRT", "WALKING A DOG", "OPENING A PRESENT", "BLOWING BUBBLES",
    "JUMPING ROPE", "RIDING A HORSE", "ROWING A BOAT", "HITCHHIKING",
    "MILKING A COW", "SAWING WOOD", "HAMMERING A NAIL", "TIEING A SHOELACE",
    "SHAVING", "PUTTING ON MAKEUP", "BRUSHING HAIR", "FLIPPING A PANCAKE",
    "PUMPING GAS", "PLAYING DRUMS", "PLAYING GUITAR", "CONDUCTING AN ORCHESTRA",
    "BALLET DANCING", "BREAKDANCING", "PRACTICING KARATE", "BOXING",
    "BOWLING", "SKATEBOARDING", "SURFING", "SKIING", "SHOOTING A BASKET",
    "KICKING A SOCCER BALL", "THROWING A FRISBEE", "PLAYING VIDEO GAMES",
    "TAKING A SELFIE", "TEXTING", "TALKING ON THE PHONE", "WHISPERING",
    "CRYING LIKE A BABY", "LAUGHING HYSTERICALLY", "SNEEZING", "HICCUPS",
    "YAWNING", "SLEEPWALKING", "SHIVERING", "SWEATING", "SCRATCHING AN ITCH",
    "CATCHING A BUTTERFLY", "PLANTING A SEED", "WATERING PLANTS", "DIGGING A HOLE",
    // ... (Imagine 400+ more similar lines here to reach 500)
    "WASHING A CAR", "BUILDING A SNOWMAN", "WRAPPING A GIFT", "BLOWING OUT CANDLES",
    "CLAPPING HANDS", "STOMPING FEET", "CRAWLING", "MARCHING", "SALUTING",
    "PEELING A BANANA", "CRACKING AN EGG", "POURING A DRINK", "DRINKING SODA",
    "EATING CORN ON THE COB", "LICKING AN ICE CREAM", "CHEWING GUM",
    "INFLATING A BALLOON", "POPPING A BALLOON", "FLYING LIKE A BIRD",
    "WADDLING LIKE A PENGUIN", "HOPPING LIKE A KANGAROO", "SLITHERING LIKE A SNAKE",
    "TRUMPETING LIKE AN ELEPHANT", "ROARING LIKE A LION", "MEOWING", "BARKING",
  ];
}