// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXjiJvVUJiC8tHlGYXP9R8ZKyvzmDba4',
    appId: '1:408037924073:web:789c542dc4671dd907e478',
    messagingSenderId: '408037924073',
    projectId: 'play-lume',
    authDomain: 'play-lume.firebaseapp.com',
    storageBucket: 'play-lume.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJjB2luh3zMH1NTHYs4K6vyXnEm_NrwPk',
    appId: '1:408037924073:android:1de08b7243b0651c07e478',
    messagingSenderId: '408037924073',
    projectId: 'play-lume',
    storageBucket: 'play-lume.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOXjiJvVUJiC8tHlGYXP9R8ZKyvzmDba4',
    appId: '1:408037924073:web:55bfa8d9594438b807e478',
    messagingSenderId: '408037924073',
    projectId: 'play-lume',
    authDomain: 'play-lume.firebaseapp.com',
    storageBucket: 'play-lume.firebasestorage.app',
  );
}
